### ISSUE TITLE
Different version of python

### ISSUE THREAD

**Issue by neelshah931** [paper-parser/paper-parser#1]
I guess all of us are still using different versions of python and CDE might not work as expected

**Comment by theomnipanda** [comment]
good point. I couldn't get ChemDataExtractor to work with python 3, so I went back to 2.7... I think. Anyone have this problem or was I dumb?

**Comment by theomnipanda** [comment]
We could solve this problem with a consistent virtual environment. My preference would be conda

**Comment by christinehc** [comment]
I have Python 3.6 and CDE has been working ~fine so far.  What issues were you having with python 3?

**Comment by theomnipanda** [comment]
> I have Python 3.6 and CDE has been working ~fine so far. What issues were you having with python 3?

When I conda installed CDE it forced python 2.7. 

How did you install CDE?

**Comment by christinehc** [comment]
https://anaconda.org/conda-forge/chemdataextractor

`conda install -c conda-forge chemdataextractor`

This worked for me

**Comment by christinehc** [comment]
from @linnetteteo:
making an environment we need for CDE:
`conda create -n py36 python=3.6`
activate environment by: `source activate py36`
`conda install -c chemdataextractor chemdataextractor`
`conda install singledispatch`
`cde data download`
