### ISSUE TITLE
Importing `chemdataextractor`

### ISSUE THREAD

**Issue by theomnipanda** [paper-parser/paper-parser#10]
Hitting the error when I try and run the example notebook `example_read_paper_&_classify.ipynb`.
![image](https://user-images.githubusercontent.com/21069601/54381470-20e6d100-464b-11e9-8a87-a4af9542617e.png)

I figured this would come up eventually, but we will need to determine the path to CDE upon installation of `paperparser`

**Comment by christinehc** [comment]
I'm not getting the same error.

**Comment by theomnipanda** [comment]
This issue was resolved by installing CDE from the condaforge channel
```conda install -c conda-forge chemdataextractor```

The instructions at http://chemdataextractor.org/docs/install are out of date, running 
```conda install -c chemdataextractor chemdataextractor```
as instructed downloads an older version of the package for python 2.7
