### ISSUE TITLE
Project pre-review

### ISSUE THREAD

**Issue by dacb** [paper-parser/paper-parser#11]
Your project is lit!  Love the README - finish it up with installation guides and a pointer to a how to use or a demo and it will super!  Great use of issues and project.  I have a few notes:

- [x] In the docs directory, please put your tech review slides and the final poster.

- [x] Your docstrings look pretty good overall, just finish a few. 

- [x] Tests look great.  I'll dive into them more but on first inspect, really nice job here.

This is really nicely done.

**Comment by theomnipanda** [comment]
just moved tech review slides and the final poster to doc directory, a well as cleaned some things up.

**Comment by theomnipanda** [comment]
Hey peoples (@linnetteteo @christinehc @neelshah931 ), can we each make sure our respective pices of the project have reasonable docstrings and tests? Plz update when complete.
