### ISSUE TITLE
Extracting synthesis sentences

### ISSUE THREAD

**Issue by christinehc** [paper-parser/paper-parser#6]
The test synthesis paragraph I am parsing is copied here: 
(source: https://www.nature.com/articles/nmat4014)

> A dense blocking layer of TiO2 (bl-TiO2, ∼70 nm in thickness) was deposited onto a F-doped SnO2 (FTO, Pilkington, TEC8) substrate by spray pyrolysis, using a 20 mM titanium diisopropoxide bis(acetylacetonate) solution (Aldrich) at 450 °C to prevent direct contact between the FTO and the hole-conducting layer. A 200–300-nm-thick mesoporous TiO2 (particle size: about 50 nm, crystalline phase: anatase) film was spin-coated onto the bl-TiO2/FTO substrate using home-made pastes14 and calcining at 500 °C for 1 h in air to remove organic components. CH3NH3I (MAI) and CH3NH3Br (MABr) were first synthesized by reacting 27.86 ml CH3NH2 (40% in methanol, Junsei Chemical) and 30 ml HI (57 wt% in water, Aldrich) or 44 ml HBr (48 wt% in water, Aldrich) in a 250 ml round-bottom flask at 0 °C for 4 h with stirring, respectively. The precipitate was recovered by evaporation at 55 °C for 1 h. MAI and MABr were dissolved in ethanol, recrystallized from diethyl ether, and dried at 60 °C in a vacuum oven for 24 h. The prepared MAI and MABr powders, PbI2 (Aldrich) and PbBr2 (Aldrich) for 0.8 M MAPb(I1 − xBrx)3 (x = 0.1–0.15) solution were stirred in a mixture of GBL and DMSO (7:3 v/v) at 60 °C for 12 h. The resulting solution was coated onto the mp-TiO2/bl-TiO2/FTO substrate by a consecutive two-step spin-coating process at 1,000 and 5,000 r.p.m for 10 and 20 s, respectively. During the second spin-coating step, the substrate (around 1 cm × 1 cm) was treated with toluene drop-casting. A detailed time-rotation profile for the spin-coating is represented in Supplementary Fig. 1c. The substrate was dried on a hot plate at 100 °C for 10 min. A solution of poly(triarylamine) (15 mg, PTAA, EM Index, Mw = 17,500 g mol−1) in toluene (1.5 ml) was mixed with 15 μl of a solution of lithium bistrifluoromethanesulphonimidate (170 mg) in acetonitrile (1 ml) and 7.5 μl 4-tert-butylpyridine and spin-coated on the MAPb(I1 − xBrx)3 (x = 0.1–0.15)/mp-TiO2/bl-TiO2/FTO substrate at 3,000 r.p.m for 30 s. Finally, a Au counterelectrode was deposited by thermal evaporation. The active area of this electrode was fixed at 0.16 cm2.

As you can see, there are multiple sentences that may contain relevant keywords (e.g. the annealing at the beginning is related to the TiO2 layer, not the perovskite film layer).

Will the "sentence finder" program be able to distinguish between these?

**Comment by linnetteteo** [comment]
@christinehc I have no idea that that wasn't part of the perovskite process (you don't want the first two sentences?). I am guessing....no. We probably need to parse the identified synthesis sentences in such a way that the steps are attributed to certain chemical entities, and just throw away those that are not perovskites?

**Comment by christinehc** [comment]
@linnetteteo @neelshah931 Yes, the first two sentences relate to one of the layers in a full device (not the perovskite layer itself; it's a zinc oxide electron transport layer).  Similarly, the last two sentences also refer to separate device layers (the hole transport layer and the electrodes).  The sentences in between all relate to the perovskite layer.

Either of our parsers could detect irrelevant information, e.g. detecting common perovskite precursors (usually end with -Br, -I, or (rarely) -Cl) and pulling those sentences, or on the opposite end, detecting TiO2 / a polymer name / other common device layers (spiro-MeOTAD/PCBM/etc.) and knowing to discard those.  If I can get the chemical association to work on my end, it would be simple for me to implement.  But that might not be the case.  I also want to make sure we know who is working on this problem, instead of both or neither team doing so, and also because it'll affect the output>input flow of our program(s)-- if your output is a sentence or sentences, it makes more sense for you to implement, but if you just want to output a paragraph, it makes more sense for me to implement.
